#!/bin/bash

if [ -z $HUBOT_HIPCHAT_JID ] || [ -z HUBOT_HIPCHAT_NAME ] || [ -z HUBOT_HIPCHAT_PASSWORD ]; then
  echo "Error: enviroment HipChat credentials missing see README for more info"
fi
if [ -z $HUBOT_HIPCHAT_JID ] ; then
  echo "Error: enviroment Redis URL credentials missing see README for more info"
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $DIR
bin/hubot -a hipchat -n cubot
popd